PROVIDERS = [
    {
        "name": "openrouter",
        "displayName": "OpenRouter",
        "envKey": "OPENROUTER_API_KEY",
        "defaultApiBase": "https://openrouter.ai/api/v1",
        "backend": "openai_compat",
        "isGateway": True,
        "supportsPromptCaching": True,
        "detectByKeyPrefix": "sk-or-",
        "testModel": "google/gemma-3-1b-it:free",
    },
    {
        "name": "anthropic",
        "displayName": "Anthropic",
        "envKey": "ANTHROPIC_API_KEY",
        "defaultApiBase": None,
        "backend": "anthropic",
        "isGateway": False,
        "supportsPromptCaching": True,
        "detectByKeyPrefix": "sk-ant-",
        "testModel": "claude-sonnet-4-20250514",
    },
    {
        "name": "openai",
        "displayName": "OpenAI",
        "envKey": "OPENAI_API_KEY",
        "defaultApiBase": None,
        "backend": "openai_compat",
        "isGateway": False,
        "supportsPromptCaching": True,
        "detectByKeyPrefix": "sk-",
        "testModel": "gpt-4o-mini",
    },
    {
        "name": "deepseek",
        "displayName": "DeepSeek",
        "envKey": "DEEPSEEK_API_KEY",
        "defaultApiBase": "https://api.deepseek.com/v1",
        "backend": "openai_compat",
        "isGateway": False,
        "supportsPromptCaching": False,
        "detectByKeyPrefix": "sk-",
        "testModel": "deepseek-chat",
    },
    {
        "name": "groq",
        "displayName": "Groq",
        "envKey": "GROQ_API_KEY",
        "defaultApiBase": "https://api.groq.com/openai/v1",
        "backend": "openai_compat",
        "isGateway": False,
        "supportsPromptCaching": False,
        "detectByKeyPrefix": "gsk_",
        "testModel": "llama-3.1-8b-instant",
    },
    {
        "name": "gemini",
        "displayName": "Google Gemini",
        "envKey": "GOOGLE_API_KEY",
        "defaultApiBase": "https://generativelanguage.googleapis.com/v1beta/openai/",
        "backend": "openai_compat",
        "isGateway": False,
        "supportsPromptCaching": True,
        "detectByKeyPrefix": "AIza",
        "testModel": "gemini-2.0-flash",
    },
    {
        "name": "siliconflow",
        "displayName": "SiliconFlow",
        "envKey": "SILICONFLOW_API_KEY",
        "defaultApiBase": "https://api.siliconflow.cn/v1",
        "backend": "openai_compat",
        "isGateway": False,
        "supportsPromptCaching": False,
        "detectByKeyPrefix": "sk-",
        "testModel": "Qwen/Qwen2.5-7B-Instruct",
    },
    {
        "name": "aihubmix",
        "displayName": "AIHubMix",
        "envKey": "AIHUBMIX_API_KEY",
        "defaultApiBase": "https://aihubmix.com/v1",
        "backend": "openai_compat",
        "isGateway": True,
        "supportsPromptCaching": False,
        "detectByKeyPrefix": "sk-",
        "testModel": "gpt-4o-mini",
    },
    {
        "name": "volcengine",
        "displayName": "Volcengine",
        "envKey": "VOLCENGINE_API_KEY",
        "defaultApiBase": "https://ark.cn-beijing.volces.com/api/v3",
        "backend": "openai_compat",
        "isGateway": False,
        "supportsPromptCaching": False,
        "detectByKeyPrefix": None,
        "testModel": "doubao-lite-4k",
    },
    {
        "name": "byteplus",
        "displayName": "BytePlus",
        "envKey": "BYTEPLUS_API_KEY",
        "defaultApiBase": "https://api.byteplus.com/api/inference",
        "backend": "openai_compat",
        "isGateway": False,
        "supportsPromptCaching": False,
        "detectByKeyPrefix": None,
        "testModel": "ByteDance-Seed",
    },
    {
        "name": "zhipu",
        "displayName": "Zhipu AI",
        "envKey": "ZHIPU_API_KEY",
        "defaultApiBase": "https://open.bigmodel.cn/api/paas/v4",
        "backend": "openai_compat",
        "isGateway": False,
        "supportsPromptCaching": False,
        "detectByKeyPrefix": None,
        "testModel": "glm-4-flash",
    },
    {
        "name": "dashscope",
        "displayName": "DashScope (Alibaba)",
        "envKey": "DASHSCOPE_API_KEY",
        "defaultApiBase": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "backend": "openai_compat",
        "isGateway": False,
        "supportsPromptCaching": True,
        "detectByKeyPrefix": "sk-",
        "testModel": "qwen-turbo",
    },
    {
        "name": "moonshot",
        "displayName": "Moonshot",
        "envKey": "MOONSHOT_API_KEY",
        "defaultApiBase": "https://api.moonshot.cn/v1",
        "backend": "openai_compat",
        "isGateway": False,
        "supportsPromptCaching": False,
        "detectByKeyPrefix": "sk-",
        "testModel": "moonshot-v1-8k",
    },
    {
        "name": "minimax",
        "displayName": "MiniMax",
        "envKey": "MINIMAX_API_KEY",
        "defaultApiBase": "https://api.minimax.chat/v1",
        "backend": "openai_compat",
        "isGateway": False,
        "supportsPromptCaching": False,
        "detectByKeyPrefix": None,
        "testModel": "MiniMax-M1",
    },
    {
        "name": "mistral",
        "displayName": "Mistral AI",
        "envKey": "MISTRAL_API_KEY",
        "defaultApiBase": "https://api.mistral.ai/v1",
        "backend": "openai_compat",
        "isGateway": False,
        "supportsPromptCaching": False,
        "detectByKeyPrefix": None,
        "testModel": "mistral-small-latest",
    },
    {
        "name": "stepfun",
        "displayName": "StepFun",
        "envKey": "STEPFUN_API_KEY",
        "defaultApiBase": "https://api.stepfun.com/v1",
        "backend": "openai_compat",
        "isGateway": False,
        "supportsPromptCaching": False,
        "detectByKeyPrefix": None,
        "testModel": "step-1-8k",
    },
    {
        "name": "xiaomiMimo",
        "displayName": "Xiaomi Mimo",
        "envKey": "XIAOMI_MIMO_API_KEY",
        "defaultApiBase": None,
        "backend": "openai_compat",
        "isGateway": False,
        "supportsPromptCaching": False,
        "detectByKeyPrefix": None,
        "testModel": "mimo-v2",
    },
    {
        "name": "qianfan",
        "displayName": "Qianfan (Baidu)",
        "envKey": "QIANFAN_API_KEY",
        "defaultApiBase": "https://qianfan.baidubce.com/v2",
        "backend": "openai_compat",
        "isGateway": False,
        "supportsPromptCaching": False,
        "detectByKeyPrefix": None,
        "testModel": "ERNIE-Speed-8K",
    },
    {
        "name": "ollama",
        "displayName": "Ollama",
        "envKey": "",
        "defaultApiBase": "http://localhost:11434/v1",
        "backend": "openai_compat",
        "isGateway": False,
        "supportsPromptCaching": False,
        "detectByKeyPrefix": None,
        "testModel": "llama3.2",
    },
    {
        "name": "vllm",
        "displayName": "vLLM",
        "envKey": "",
        "defaultApiBase": "http://localhost:8000/v1",
        "backend": "openai_compat",
        "isGateway": False,
        "supportsPromptCaching": True,
        "detectByKeyPrefix": None,
        "testModel": None,
    },
    {
        "name": "ovms",
        "displayName": "OpenVINO Model Server",
        "envKey": "",
        "defaultApiBase": "http://localhost:8001/v1",
        "backend": "openai_compat",
        "isGateway": False,
        "supportsPromptCaching": False,
        "detectByKeyPrefix": None,
        "testModel": None,
    },
    {
        "name": "azureOpenai",
        "displayName": "Azure OpenAI",
        "envKey": "AZURE_OPENAI_API_KEY",
        "defaultApiBase": None,
        "backend": "azure_openai",
        "isGateway": False,
        "supportsPromptCaching": True,
        "detectByKeyPrefix": None,
        "testModel": None,
    },
    {
        "name": "custom",
        "displayName": "Custom",
        "envKey": "",
        "defaultApiBase": None,
        "backend": "openai_compat",
        "isGateway": False,
        "supportsPromptCaching": False,
        "detectByKeyPrefix": None,
        "testModel": None,
    },
]

PROVIDER_MAP = {p["name"]: p for p in PROVIDERS}
